# This is the network config written by 'subiquity'
network:
  ethernets:
    # Далее идёт описание сетевого интерфейса enp0s3.
    enp0s3:
      # Ему будет назначен фиксированный IP-адрес.
      # Кроме адреса, нужно присвоить маску сети
      addresses: [192.168.1.100/24]
      dhcp4: false
      nameservers:
        addresses: [8.8.8.8]
      routes:
        - to: default
          via: 192.168.1.1
        - to: 192.168.2.0/24
          via: 192.168.1.100
        - to: 192.168.10.100
          via: 192.168.1.1
  version: 2
